# Generated by Django 2.0.2 on 2018-03-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='folio',
            new_name='id',
        ),
    ]
